=== Aliaksiej-Ramanchuk/Theatre/Сайт тэатра/performances.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="name" type="xs:string"></xs:element>
    <xs:element name="age" type="xs:nonNegativeInteger"></xs:element>
    <xs:element name="description" type="xs:string"></xs:element>
    <xs:element name="author" type="xs:string"></xs:element>
    <xs:element name="producer" type="xs:string"></xs:element>
    <xs:element name="painter" type="xs:string"></xs:element>
    <xs:element name="duration" type="xs:string"></xs:element>
    <xs:element name="date" type="xs:string"></xs:element>
    <xs:element name="image" type="xs:string"></xs:element>

    <xs:element name="performance">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"></xs:element>
                <xs:element ref="age"></xs:element>
                <xs:element ref="description"></xs:element>
                <xs:element ref="author"></xs:element>
                <xs:element ref="producer"></xs:element>
                <xs:element ref="painter"></xs:element>
                <xs:element ref="duration"></xs:element>
                <xs:element ref="date"></xs:element>
                <xs:element ref="image"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="performances">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="performance" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Aliaksiej-Ramanchuk/Theatre/Сайт тэатра/performances.xml
<?xml version="1.0" encoding="UTF-8"?>

<performances xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="performances.xsd">
    <performance>
        <name>Паўлінка</name>
        <age>12</age>
        <description>сцэны са шляхоцкага жыцця</description>
        <author>Янка Купала</author>
        <producer>Л.Літвінаў</producer>
        <painter>Б.Малкін</painter>
        <duration>2 гадзіны</duration>
        <date>30.02.2022 а 18:00</date>
        <image>images/performances/paulinka.jpg</image>
    </performance>
</performances>
